language: python
script:
- pytest
env:
  global:
    secure: NRWGDe1CUiNZmtzCOvSVglZGmVRx7XYzpulhIqrtygewnmJ5X09m4Y2b2UHDn05cdHTAtpAwrFN/5h5mWirGQVS1ccQ6Lq25tFpJHLISAtaenNGfdh7avuC2+g2D13Bv9f52I668N1NA7kM4QH2DmUhAuBHq09GQVyqJRaopJnkEfHQNmkiDrEQpK8YysAESNUjLWU9Eth9fFdjyFmPjdfMVAIyGd64cSeDXL77HE6lFgnPP+m58cZveFPIxn2UHffkl/8+/9JXJPYLJ7rbdrfskCxuCA38krghfG1F54dN7j+K7Y9Z29cSjHUkGK2GeLlR3mLtIIf/1ICTVsra/NbrCtm+9L5lLQE5T2898hJLURPyCGGNJrWABVDaSTciBbkW2IZsUtNBIbaFPvkMnF4IdANa11qRi+q/WgIzfpCNdGCormdKxnEmVPMCIR93KDkD8JI8yIRiG0H5+2vjIwCSXyEDkhRUP5NQ0L2b4WvOmJDLrb6q86AsECN875yQDRVZ11dmYyTS46z7BPGluJlNn1qOQbx1BQ2U0T14ioJnhYPBMrJI8eekdQ2fRsFagHZQlRhXnMmQkj+/VpKwZwrgonRozH9aBsMEDSvNbMxTvX0gY3ZiaQy5jeZWE5BDQ3ECdV4LRFk3ZX14/LE0J6FkuRPcMF3QX//BDK0fZcl4=

